[package]
name = "y2019d02"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "y2019d02"
path = "src/02.rs"

[dependencies]
aoclib = { git = "https://github.com/BlockOG/aoclib" }
parse-display = "0.8.2"
rustc-hash = "1.1.0"
intcode = { path = "../intcode" }
