[package]
name = "y2016d03"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "y2016d03"
path = "src/03.rs"

[dependencies]
aoclib = { git = "https://github.com/BlockOG/aoclib" }
itertools = "0.12.0"
