[package]
name = "y2015d07"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "y2015d07"
path = "src/07.rs"

[dependencies]
aoclib = { git = "https://github.com/BlockOG/aoclib" }
parse-display = "0.8.2"
rustc-hash = "1.1.0"
