[package]
name = "y2016d04"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "y2016d04"
path = "src/04.rs"

[dependencies]
aoclib = { git = "https://github.com/BlockOG/aoclib" }
parse-display = "0.8.2"
