[package]
name = "y2023d22"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "y2023d22"
path = "src/22.rs"

[dependencies]
aoclib = { git = "https://github.com/BlockOG/aoclib" }
parse-display = "0.8.2"
rayon = "1.8.0"
rustc-hash = "1.1.0"
