[package]
name = "y2023d20"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "y2023d20"
path = "src/20.rs"

[dependencies]
aoclib = { git = "https://github.com/BlockOG/aoclib" }
parse-display = "0.8.2"
rustc-hash = "1.1.0"
value-to-index = { version = "0.1.0", path = "../../value-to-index" }
