[package]
name = "y2023d09"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "y2023d09"
path = "src/09.rs"

[dependencies]
aoclib = { git = "https://github.com/BlockOG/aoclib" }
itertools = "0.12.0"
parse-display = "0.8.2"
rustc-hash = "1.1.0"
